select distinct 
    PROJECT.NAME as Project_Name , 
    SAMPLE.SAMPLE_NUMBER as Sample_Number , 
    SAMPLE.TEXT_ID as Sample_ID , 
    SAMPLE.STATUS as Sample_Status , 
    SAMPLE.PRODUCT as Product , 
    SAMPLE.MATERIAL_NAME as Material_Name , 
    TEST.ANALYSIS as Analysis , 
    TEST.REPLICATE_COUNT as Replicate , 
    RESULT.NAME as Result_Name , 
    RESULT.FORMATTED_ENTRY as Result , 
    SAMPLE.SAMPLE_NUMBER  
from ((((((
    SAMPLE
    INNER JOIN PROJECT ON SAMPLE.PROJECT = PROJECT.NAME) 
    INNER JOIN TEST ON SAMPLE.SAMPLE_NUMBER = TEST.SAMPLE_NUMBER) 
    INNER JOIN RESULT ON TEST.TEST_NUMBER = RESULT.TEST_NUMBER) 
    LEFT JOIN UNITS ON RESULT.UNITS = UNITS.UNIT_CODE) 
    INNER JOIN PRODUCT ON SAMPLE.PRODUCT = PRODUCT.NAME and SAMPLE.PRODUCT_VERSION = PRODUCT.VERSION) 
    INNER JOIN X_MATERIAL ON SAMPLE.MATERIAL_NAME = X_MATERIAL.NAME) 
where  (
    SAMPLE.GROUP_NAME IN ( 'FELR' , 'CAR' , 'RHE' , 'SYSTEM_ANALYSIS' , 'CHEM_INV' , 'POLY' , 'DEFAULT' , 'MEC'))
        